// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://lqrmkpqfofmuzrcopgza.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imxxcm1rcHFmb2ZtdXpyY29wZ3phIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjgzNjA5MjMsImV4cCI6MjA4MzkzNjkyM30.rmcWZ0eCxzApZBlapgqDwE4UIDD5JJCgovlWB3Es9ws";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);